name: Despliegue

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
      - name: Depedencias
        run: npm ci
      - name: Lint
        run: npm run lint

  build:
    needs: [linter]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
      - name: Depedencias
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  unit-test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
      - name: Depedencias
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Test
        run: npm run test

  e2e-test:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
      - name: Depedencias
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: browsers
        run: npx playwright install --with-deps
      - name: e2e
        run: npm run e2e

  deploy:
    needs: [unit-test, e2e-test]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ secrets.NAME_APP }}
          token: ${{ secrets.ACTION_KEY_COSMICCAT }}
